sudo: required
os: linux
language: minimal
services:
  - docker

install: skip
script:
  - env > .env
  - docker-compose up --build --abort-on-container-exit testpostgres prod-ci-deploy

branches:
  only:
  - master

