sudo: required
os: linux
language: java
services:
  - docker

install: skip
script:
  - export ENV_FILE=/tmp/.env && env > ${ENV_FILE}
  - docker-compose up --build --abort-on-container-exit prod-ci-deploy

branches:
  only:
  - master

