version: '2'
services:

## PRODUCTION BUILD


  # Build project java docker image
  prod-java-bookmark-notes:
    build:
      context: .
      dockerfile: Dockerfile.java

  # Build project linux binary docker image
  prod-linux-bookmark-notes:
    build:
      context: .
      dockerfile: Dockerfile.linux

  # Build the project binaries, create a git tag and upload the archives to github releases
  prod-ci-deploy:
    build:
      context: .
      dockerfile: Dockerfile.ci
    environment:
      - CURRENT_BRANCH=$TRAVIS_BRANCH # current branch name
      - REPO_TOKEN=$REPO_TOKEN # github token to deploy the binary
    volumes:
      - ./:/app
      - $HOME/.gitconfig:/root/.gitconfig

  testpostgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    hostname: testpostgres
    volumes:
      - ./src/main/docker/postgres/db/:/docker-entrypoint-initdb.d/

## DEVELOPMENT

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
      - HOSTNAMES=bookmark-notes-postgres.docker
    ports:
      - 5434:5432
