version: '2'
services:

## PRODUCTION BUILD

  prod-image-build:
    image: defreitas/bookmark-notes
    build:
      context: .

  # build the api and make the github release
  prod-ci-deploy:
    build:
      context: .
      dockerfile: Dockerfile.ci
    environment:
      - CURRENT_BRANCH=$TRAVIS_BRANCH # current branch name
      - REPO_TOKEN=$REPO_TOKEN # github token to deploy the binary
    volumes:
      - ./:/app
      - $HOME/.gitconfig:/root/.gitconfig

  testpostgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    hostname: testpostgres
    volumes:
      - ./src/main/docker/postgres/db/:/docker-entrypoint-initdb.d/

## DEVELOPMENT

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
    ports:
      - 5434:5432
