version: '3'
services:

  bookmark-notes:
    image: defreitas/bookmark-notes:3.0.7-native
    environment:
      - DATASOURCES_DEFAULT_JDBC_URL=jdbc:postgresql://postgres:5432/db?currentSchema=bookmarks
    ports:
      - 8080:8080

  postgres:
    image: postgres:10.3
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=db
